/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.szkolnecos;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.Normalizer;
/**
 *
 * @author Cyan_Lambda
 */
public class szkolneCosJ extends javax.swing.JFrame {
    

    /**
     * Creates new form szkolneCosJ
     */
    public szkolneCosJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        JLOcena = new javax.swing.JLabel();
        JLImie = new javax.swing.JLabel();
        JLNazwisko = new javax.swing.JLabel();
        JLKlasa = new javax.swing.JLabel();
        JLPrzedmiot = new javax.swing.JLabel();
        JBZapisz = new javax.swing.JButton();
        JLImie1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA = new javax.swing.JTextArea();
        JTImie = new javax.swing.JTextField();
        JBWczytaj = new javax.swing.JButton();
        JTNazwisko = new javax.swing.JTextField();
        JCKlasa = new javax.swing.JComboBox<>();
        JCPrzedmiot = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));

        jSlider1.setBackground(new java.awt.Color(15, 15, 15));
        jSlider1.setForeground(new java.awt.Color(73, 140, 138));
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(6);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(5);

        JLOcena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLOcena.setForeground(new java.awt.Color(73, 140, 138));
        JLOcena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLOcena.setText("Ocena:");

        JLImie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLImie.setForeground(new java.awt.Color(73, 140, 138));
        JLImie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLImie.setText("Podaj Imię:");

        JLNazwisko.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNazwisko.setForeground(new java.awt.Color(73, 140, 138));
        JLNazwisko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLNazwisko.setText("Podaj Nazwisko:");

        JLKlasa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLKlasa.setForeground(new java.awt.Color(73, 140, 138));
        JLKlasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLKlasa.setText("Klasa:");

        JLPrzedmiot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLPrzedmiot.setForeground(new java.awt.Color(73, 140, 138));
        JLPrzedmiot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLPrzedmiot.setText("Przedmiot:");

        JBZapisz.setBackground(new java.awt.Color(31, 31, 31));
        JBZapisz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBZapisz.setForeground(new java.awt.Color(73, 140, 138));
        JBZapisz.setText("Zapisz Dane");
        JBZapisz.setBorder(null);
        JBZapisz.setBorderPainted(false);
        JBZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBZapiszActionPerformed(evt);
            }
        });

        JLImie1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLImie1.setForeground(new java.awt.Color(73, 140, 138));
        JLImie1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLImie1.setText("Wszystkie wpisy:");

        JTA.setBackground(new java.awt.Color(31, 31, 31));
        JTA.setColumns(20);
        JTA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JTA.setForeground(new java.awt.Color(73, 140, 138));
        JTA.setRows(5);
        JTA.setBorder(null);
        jScrollPane1.setViewportView(JTA);

        JTImie.setBackground(new java.awt.Color(31, 31, 31));
        JTImie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTImie.setForeground(new java.awt.Color(73, 140, 138));
        JTImie.setText("Jakub");
        JTImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTImieActionPerformed(evt);
            }
        });

        JBWczytaj.setBackground(new java.awt.Color(31, 31, 31));
        JBWczytaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBWczytaj.setForeground(new java.awt.Color(73, 140, 138));
        JBWczytaj.setText("Wczytaj dane");
        JBWczytaj.setBorder(null);
        JBWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBWczytajActionPerformed(evt);
            }
        });

        JTNazwisko.setBackground(new java.awt.Color(31, 31, 31));
        JTNazwisko.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTNazwisko.setForeground(new java.awt.Color(73, 140, 138));
        JTNazwisko.setText("Kos");

        JCKlasa.setBackground(new java.awt.Color(15, 15, 15));
        JCKlasa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JCKlasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1PTN", "2PTN", "3PTN", " " }));
        JCKlasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCKlasaActionPerformed(evt);
            }
        });

        JCPrzedmiot.setBackground(new java.awt.Color(15, 15, 15));
        JCPrzedmiot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JCPrzedmiot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematyka", "Niemiecki", "Angielski", "Polski" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLKlasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLPrzedmiot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLImie, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTImie)
                            .addComponent(JTNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(JCKlasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JCPrzedmiot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLImie1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBWczytaj))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLImie, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLImie1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBWczytaj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JCKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLPrzedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCPrzedmiot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLOcena, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(JBZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBZapiszActionPerformed
        //setting var
        String Name = JTImie.getText();
        String Surname = JTNazwisko.getText();
        String Klasa = JCKlasa.getSelectedItem().toString();
        String Przedmiot = JCPrzedmiot.getSelectedItem().toString();
        int Ocena = jSlider1.getValue();
        String Com = Name +";"+Surname+";"+Klasa+";"+Przedmiot+";"+Ocena;
        System.out.println(Com);
        
        //normalize
        String SName = Normalizer.normalize(Name, Normalizer.Form.NFD);
        SName = SName.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
        String SSurname = Normalizer.normalize(Surname, Normalizer.Form.NFD);
        SSurname = SSurname.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
        
        //Write to file
        PrintWriter writer = null;
        try {
            writer = new PrintWriter(SName+"_"+SSurname+".txt", "UTF-8");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(szkolneCosJ.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(szkolneCosJ.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.println(Com);
        writer.close();
    }//GEN-LAST:event_JBZapiszActionPerformed

    private void JBWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBWczytajActionPerformed
        JTA.setText(JTA.getText() + Com);
        
    }//GEN-LAST:event_JBWczytajActionPerformed

    private void JCKlasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCKlasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCKlasaActionPerformed

    private void JTImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTImieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTImieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(szkolneCosJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(szkolneCosJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(szkolneCosJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(szkolneCosJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new szkolneCosJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBWczytaj;
    private javax.swing.JButton JBZapisz;
    private javax.swing.JComboBox<String> JCKlasa;
    private javax.swing.JComboBox<String> JCPrzedmiot;
    private javax.swing.JLabel JLImie;
    private javax.swing.JLabel JLImie1;
    private javax.swing.JLabel JLKlasa;
    private javax.swing.JLabel JLNazwisko;
    private javax.swing.JLabel JLOcena;
    private javax.swing.JLabel JLPrzedmiot;
    private javax.swing.JTextArea JTA;
    private javax.swing.JTextField JTImie;
    private javax.swing.JTextField JTNazwisko;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
